### ISSUE TITLE
Carte moteur DC + encodeur

### ISSUE THREAD

**Issue by BloodFutur** [ClubRobotInsat/robot-2023#11]
# À faire
- [x] Souder les 4 ponts en H en prototype
- [x] Ajouter pins pour PWM
- [x] Ajouter pins/ proto pour avoir les pins de roue encodeuse
- [x] Faire conception KiCAD
- [x] Tester la carte KiCAD
- [x] Commander carte

**Comment by Cornelius-Sivertsen** [comment]
Carte commandé, je marque l'issue comme fermée.
Attention qui'il faut tuojours tester la carte physique.
