### ISSUE TITLE
Carte Alimentation 5V

### ISSUE THREAD

**Issue by BloodFutur** [ClubRobotInsat/robot-2023#7]
### À faire:

- [x]  Concevoire l’architecture de la carte
- [x]  Faire les tests de fonctionnement et valider le concept
- [x]  Passer sur KiCad (Travailler ensemble sur la même carte en passant par Git)
- [x]  Faire les PCBs de test avec GEI et/ou FabLab
- [ ]  Commander des PCBs en Chine ou en France (à voire)

**Comment by Cornelius-Sivertsen** [comment]
Changed architecture to have one unit for 5V, 12V, and 7.4V. Marking issue as (close as not planned).
